### ISSUE TITLE
Min required php version

### ISSUE THREAD

**Issue by m-rybak** [gugglegum/phpstorm-reset-trial#1]
Hi, you need to add "min required php version 7.1.x" information in README, because i have trouble with php 7.0.x. 
Lower version don't support 'void' return value
``` php 

PhpStorm Reset Trial ver. 1.0.0 2018-09-26

This utility will reset trail period of your PhpStorm installation with saving its settings.

Config directory in "/home/user/.PhpStorm2018.2/config"
Backup directory in "/home/user/.PhpStorm2018.2/backup"

Want to continue? (y/n) [no] y
Making backup folder ... OK
Move config folder to backup. PhpStorm must be closed. Are you ready? (y/n) [no] y
Moving config folder to backup ... OK
PHP Fatal error:  Uncaught TypeError: Return value of App\Steps\Step01::forward() must be an instance of App\Steps\void, none returned in phar:///home/user/phpstorm_reset_trial.phar/app/Steps/Step01.php:79
Stack trace:
#0 phar:///home/user/phpstorm_reset_trial.phar/app/PhpstormResetTrial.php(59): App\Steps\Step01->forward()
#1 phar:///home/user/phpstorm_reset_trial.phar/app/PhpstormResetTrial.php(22): App\PhpstormResetTrial->run()
#2 phar:///home/user/phpstorm_reset_trial.phar/bin/phpstorm_reset_trial(18): App\PhpstormResetTrial::main()
#3 /home/user/phpstorm_reset_trial.phar(10): require('phar:///home/us...')
#4 {main}
  thrown in phar:///home/user/phpstorm_reset_trial.phar/app/Steps/Step01.php on line 79
```

**Comment by gugglegum** [comment]
I'll downgrade my code to run on php 7.0 today. Thank you for notice.

**Comment by gugglegum** [comment]
Try version 1.0,1 I just released. It should run on PHP 7.0.

**Comment by m-rybak** [comment]
ok, thx
